version:  "3.9"

services:

  radius:
    image: johnreah/radius
    ports:
      - "1812-1813:1812-1813/udp"
    command: -X
    depends_on:
      - database

  database:
    image: johnreah/radius-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - radius-mysql-volume:/var/lib/mysql

volumes:
  radius-mysql-volume:
