FROM mariadb

ENV MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

WORKDIR /docker-entrypoint-initdb.d

COPY mysql/files/*.sql .

RUN cat 01-create-database.sql 02-create-schema.sql 03-create-user.sql > db-init.sql && \
    rm 01-create-database.sql 02-create-schema.sql 03-create-user.sql && \
    pwd && ls -al

#RUN apt update && \
#    apt install -y ncat

#CMD nohup /etc/raddb/healthcheck.sh & freeradius -X
